config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :products

  # Defines the root path route ("/")
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true   
    validates :price, presence: true, numericality: {:greater_than => 0}   
    validates :short_description, presence: true   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET method to get all products from the database
  def index
    @products = Product.all
  end

  # GET method to get a product by id
  def show
    @product = Product.find(params[:id])
  end

  # GET method for the new product form
  def new
    @product = Product.new
  end

  # POST method for processing form data
  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'Product added!'
      redirect_to root_path
    else
      flash[:error] = 'Failed to add product!'
      render :new
    end
  end

  # GET method for editing a product based on id
  def edit
    @product = Product.find(params[:id])
  end

  # PUT method for updating in the database a product based on id
  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = 'Product updated!'
      redirect_to products_path
    else
      flash[:error] = 'Failed to update product!'
      render :edit
    end
  end

  # DELETE method for deleting a product from the database based on id
  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:notice] = 'Product deleted!'
    else
      flash[:error] = 'Failed to delete this product!'
    end
    redirect_to root_path
  end

  # Strong parameters for the validation of params
  private

  def product_params
    params.require(:product).permit(:name, :price, :short_description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
       <%= stylesheet_link_tag 'https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.css' %>
       <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
       <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= stylesheet_link_tag 'products_index', media: 'all' %><%= stylesheet_link_tag 'products', media: 'all' %>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
       <%= stylesheet_link_tag 'products_crud', media: 'all' %>
       <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <div class="container">  
<div><% if flash[:notice] %>  
<div><%= flash[:notice] %></div>  
<% end %> <%= yield %></div>  
</div>  
</div>  
    <%= javascript_include_tag 'https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.js' %>  
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>  
  </body>
</html>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>
<div class="container">   
  <%= form_for @product, url: { action: :update }, method: :patch do |f| %>   
    <h3>Edit Product</h3>   
    <%= "<div>#{flash[:error]}</div>".html_safe if flash[:error].present? %>
    <p>   
      <div>   
        <label>Product Name</label>   
        <%= f.text_field :name %>   
      </div>   
      <div>   
        <label>Price</label>   
        <%= f.text_field :price %>   
      </div>   
      <div>   
        <label>Description</label>   
        <%= f.text_field :short_description %>   
      </div>   
    </p>   
    <div>   
      <%= link_to 'Back', products_path %>   
      <%= f.submit 'Update Product' %>   
    </div>   
  <% end %>   
</div>

app/views/products/index.html.erb
<!DOCTYPE html>
<html>
<body>
  <div class="container">
    <h3>STOCK LIST</h3>
     
    <div>
      <%= link_to 'Add Product', new_product_path %>
    </div>
    <br>
    
    <table border="2">
      <thead>
        <tr>
          <th>Name</th>
          <th>Price</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.price %></td>
            <td><%= truncate(product.short_description, length: 75) %></td>
            <td>
              <%= link_to 'Show', product_path(product) %>
              <%= link_to 'Edit', edit_product_path(product) %>
              <%= link_to 'Delete', product_path(product), method: :delete %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</body>
</html>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>
<div class="container">   
  <%= form_for @product, url: {action: :create} do |f| %>   
      <div>   
        <h3>Add a Product</h3>   
      </div>   
      <div>   
        <p>   
          <%= "<div>#{@product.errors.full_messages.first}</div>".html_safe if @product.errors.any? %>   
        <div>   
            <label>Product Name</label>   
              <%= f.text_field :name %>   
        </div>   
  
        <div>   
             <label>Price</label>   
             <%= f.text_field :price %>   
        </div>   
  
        <div>   
           <label>Description</label>   
              <%= f.text_field :short_description %>   
        </div>   
         </p>   
      </div>   
      <div>   
        <%= link_to 'Back', { controller: 'products', action: 'index'} %>   
        <%= f.submit 'Create Product' %>   
      </div>   
  <% end %>   
</div>  

app/views/products/show.html.erb
<h1>Product Details</h1>

<div class="container">
  <h3>Product Information</h3>

  <div>
    <label>Product Name:</label>
    <%= @product.name %>
  </div>

  <div>
    <label>Price:</label>
    <%= @product.price %>
  </div>

  <div>
    <label>Description:</label>
    <%= @product.short_description %>
  </div>

  <div class="actions">
    <%= button_to 'Delete Product', @product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    <%= link_to 'Back to Products', products_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>